//! Apps in the Start menu ("All apps"): listing and launching.
//!
//! The source is Windows' Applications folder (shell:AppsFolder): classic programs and Store apps come
//! together, with their Start menu names. Launching also goes through that folder
//! (`explorer.exe shell:AppsFolder\<id>`), so one path covers both kinds.

use std::process::Command;

use anyhow::{Context, Result, anyhow};
use serde::Serialize;
use windows::Win32::System::Com::{COINIT_APARTMENTTHREADED, CoInitializeEx, CoTaskMemFree, CoUninitialize, IBindCtx};
use windows::Win32::UI::Shell::{
    BHID_EnumItems, FOLDERID_AppsFolder, IEnumShellItems, IShellItem, KF_FLAG_DEFAULT, SHGetKnownFolderItem, SIGDN,
    SIGDN_NORMALDISPLAY, SIGDN_PARENTRELATIVEPARSING,
};

use crate::i18n::Msg;

#[derive(Debug, Clone, Serialize)]
pub struct App {
    pub name: String,
    /// AppUserModelID or program path; used when launching
    pub id: String,
    /// Store (packaged) app
    pub store: bool,
}

/// Start menu entries that are not apps: web links, documents, uninstallers.
fn is_app(name: &str, id: &str) -> bool {
    let id = id.to_lowercase();
    let link = id.starts_with("http://") || id.starts_with("https://");
    let doc = [".txt", ".htm", ".html", ".chm", ".url", ".pdf"].iter().any(|e| id.ends_with(e));
    !(link || doc || name.to_lowercase().starts_with("uninstall"))
}

/// App list sorted by name.
pub fn list() -> Result<Vec<App>> {
    // Shell objects need a single-threaded COM apartment; this runs on its own thread so it does not depend
    // on the caller's COM setup.
    std::thread::spawn(|| unsafe {
        let com = CoInitializeEx(None, COINIT_APARTMENTTHREADED).is_ok();
        let r = enumerate();
        if com {
            CoUninitialize();
        }
        r
    })
    .join()
    .map_err(|_| anyhow!("could not read the app list"))?
}

fn enumerate() -> Result<Vec<App>> {
    let mut out = Vec::new();
    unsafe {
        let folder: IShellItem = SHGetKnownFolderItem(&FOLDERID_AppsFolder, KF_FLAG_DEFAULT, None)?;
        let items: IEnumShellItems = folder.BindToHandler(None::<&IBindCtx>, &BHID_EnumItems)?;
        loop {
            let mut batch: [Option<IShellItem>; 32] = Default::default();
            let mut n = 0u32;
            items.Next(&mut batch, Some(&mut n))?;
            if n == 0 {
                break;
            }
            for item in batch.iter().take(n as usize).flatten() {
                let (Some(name), Some(id)) =
                    (display_name(item, SIGDN_NORMALDISPLAY), display_name(item, SIGDN_PARENTRELATIVEPARSING))
                else {
                    continue;
                };
                if is_app(&name, &id) {
                    out.push(App { store: id.contains('!'), name, id });
                }
            }
        }
    }
    out.sort_by_key(|a| a.name.to_lowercase());
    Ok(out)
}

fn display_name(item: &IShellItem, kind: SIGDN) -> Option<String> {
    unsafe {
        let p = item.GetDisplayName(kind).ok()?;
        let s = p.to_string().ok();
        CoTaskMemFree(Some(p.0 as *const _));
        s.filter(|s| !s.is_empty())
    }
}

/// Launches an app from the list. Ids not in the list are refused, so no arbitrary path reaches explorer.
/// The app is not a child process of strcu and stays open when strcu exits.
pub fn launch(id: &str) -> Result<App> {
    let app = list()?.into_iter().find(|a| a.id == id).context(Msg::new("err.no_app"))?;
    let windir = std::env::var("WINDIR").unwrap_or_else(|_| r"C:\Windows".into());
    Command::new(format!(r"{windir}\explorer.exe"))
        .arg(format!(r"shell:AppsFolder\{}", app.id))
        .spawn()
        .context(Msg::new("err.launch_failed"))?;
    Ok(app)
}

#[cfg(test)]
mod tests {
    use super::is_app;

    #[test]
    fn non_apps_are_filtered_out() {
        assert!(is_app("Calculator", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"));
        assert!(is_app("Example App", r"{6D809377-6AF0-444B-8957-A3773F02200E}\Example\example.exe"));
        assert!(is_app("Some Game", "steam://rungameid/123456"));
        assert!(!is_app("Node.js website", "https://nodejs.org/"));
        assert!(!is_app("PuTTY Web Site", r"{6D809377-6AF0-444B-8957-A3773F02200E}\PuTTY\website.url"));
        assert!(!is_app("WinRAR help", r"{6D809377-6AF0-444B-8957-A3773F02200E}\WinRAR\WinRAR.chm"));
        assert!(!is_app("Uninstall Node.js", "Microsoft.AutoGenerated.{1D719D94-D041-5E2F-1BF6-98EEDE508FBF}"));
    }
}
